EXTRA_SOURCE = ../common/xio.c ../common/xosera_ansiterm.c ../common/kbd.c lapi.c lcode.c lctype.c ldebug.c ldo.c ldump.c lfunc.c lgc.c llex.c lmem.c lobject.c lopcodes.c lparser.c lstate.c lstring.c ltable.c ltm.c lundump.c lvm.c lzio.c lauxlib.c lbaselib.c lcorolib.c ldblib.c liolib.c lmathlib.c loadlib.c loslib.c lstrlib.c ltablib.c lutf8lib.c linit.c
EXTRA_CC_ARGS = -D XIO -D DEBUG=1
LDFILE = ./program.ld

include ../common/program.mk
