EXTRA_SOURCE = ../common/xio.c ../common/xosera_ansiterm.c ../common/kbd.c dhry_1.c dhry_2.c
EXTRA_CC_ARGS = -D XIO -Wno-implicit-function-declaration -Wno-implicit-int
LDFILE = ./program.ld

include ../common/program.mk
