YOSYS := $(OSS_CAD_SUITE_PATH)yosys
ECPPACK := $(OSS_CAD_SUITE_PATH)ecppack
NEXTPNR := $(OSS_CAD_SUITE_PATH)nextpnr-ecp5
FUJPROG := $(OSS_CAD_SUITE_PATH)fujprog

# ******* project, board and chip name *******
BOARD = ulx3s
# 12 25 45 85
DEVICE := 85k
PACKAGE := CABGA381

PIN_DEF := ulx3s_v31.lpf
TOP_MODULE = ulx3s_v31_top
TOP_MODULE_FILE = $(TOP_MODULE).sv

SRC = \
  $(TOP_MODULE_FILE) \
  pll_cpu.v \
  pll_sdram.v \
  ../soc_top.sv \
  ../prom.v \
  ../cache_controller.v \
  ../sdram.v \
  ../ps2kbd.v \
  ../ps2mouse.v \
  ../usb/phy.v \
  ../usb/regs.v \
  ../usb/sie.v \
  ../uart_rx.v \
  ../uart_tx.v \
  ../spi.v \
  ../riscv/processor.sv \
	../riscv/alu.sv \
	../riscv/register_file.sv \
	../riscv/decoder.sv \
	../riscv/divider.v \
	../riscv/multiplier.v \
  ../video.v \
  ../rgb565_to_rgb888.sv \
  ../bram32bit.v \
  ../lattice/ecp5pll.sv \
  ../bram_true2p_2clk.v \
  ../vqueue.v \
  ../dvi/hdmi_interface.v \
  ../../external/graphite/rtl/graphite.sv \
  ../../external/graphite/rtl/reciprocal.sv \
  ../../external/graphite/rtl/div.sv

DEFINES =

ifeq ($(VIDEO),480p)
DEFINES += -DVIDEO_480P
endif

ifeq ($(VIDEO),720p)
DEFINES += -DVIDEO_720P
endif

ifeq ($(VIDEO),1080p)
DEFINES += -DVIDEO_1080P
endif

ifeq ($(CPU_SPEED),fast)
DEFINES += -DFAST_CPU
endif

DEFINES += -DVIDEO -DPS2_KBD -DPS2_MOUSE -DUSB

all: bios top.bin

clean:
	rm -f *.hex *.asc *.json *.bin *.log

bios:
	make -C ../../src/firmware

top.json: $(SRC)
	$(YOSYS) -ql top.log -p 'verilog_defines $(DEFINES) ; read_verilog -sv $(SRC); synth_ecp5 -top $(TOP_MODULE) -json top.json -abc9'

top.asc: top.json $(PIN_DEF)
	$(NEXTPNR) -l top_nextpnr.log --$(DEVICE) --package $(PACKAGE) --json top.json --lpf $(PIN_DEF) --textcfg top.asc --randomize-seed --timing-allow-fail

top.bin: top.asc
	$(ECPPACK) --compress --input top.asc --bit top.bin

prog: bios top.bin
	$(FUJPROG) -T bit top.bin

.PHONY: all prog bios
