EXTRA_SOURCE = ../../external/graphite/common/graphite.c ../../external/graphite/common/teapot.c
EXTRA_CC_ARGS = -I ../../external/graphite/common
LDFILE = ./program.ld
SEND_DELAY = 0.0003

include ../common/program.mk
