EXTRA_SOURCE = program.c ../../external/graphite/common/graphite.c ../../external/graphite/common/cube.c ../../external/graphite/common/teapot.c ../../external/graphite/common/tex32x32.c ../../external/graphite/common/tex64x64.c
EXTRA_CC_ARGS = -I../../external/graphite/common -DRV_FIXED_POINT_EXTENSION=1
include ../program.mk
