EXTRA_SOURCE = ../../external/graphite/common/graphite.c ../../external/graphite/common/cube.c ../common/kbd.c
EXTRA_CC_ARGS = -I ../../external/graphite/common
LDFILE = ./program.ld

include ../common/program.mk
